#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=$PATH:/Users/Shared/SDK/platform-tools
export PATH=$PATH:/Users/Shared/SDK/tools
export ANDROID_HOME=/Users/Shared/SDK
# ref: http://stackoverflow.com/questions/6588390/where-is-java-home-on-osx-sierra-10-12-el-captain-10-11-yosemite-10-10
export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"

alias gst="git status"
alias gaa="git add -A"
alias gca="git commit -am"
alias rn="react-native"
alias rs="react-native start"

alias cat="ccat"
alias llint=./node_modules/.bin/eslint

# overide prezto rm alias
alias rm="rm"
export PATH="$HOME/.fastlane/bin:$PATH"


export PATH="$HOME/.yarn/bin:$PATH"
alias gcc="/usr/local/Cellar/gcc/6.3.0_1/bin/gcc-6"
alias g++="/usr/local/Cellar/gcc/6.3.0_1/bin/g++-6"
# alias plantuml='java -jar /usr/local/bin/plantuml.jar'

export PATH="/usr/local/opt/gettext/bin:$PATH"
export PATH="/Users/admin/.google-cloud-sdk/bin:$PATH"
export PATH="/Users/admin/working/go_path/bin:$PATH"
export GOPATH="/Users/admin/working/go_path"
alias nf=nodes_mgmt

source /usr/local/etc/profile.d/autojump.sh
alias bfg="java -jar /usr/local/bin/bfg-1.12.16.jar"

export WORKON_HOME=$HOME/python_virts
export PROJECT_HOME=$HOME/Devel
source /usr/local/bin/virtualenvwrapper.sh
source /usr/local/share/zsh/site-functions/git-flow-completion.zsh

export FII_DATA_PATH=/Users/admin/working/health-parser/data